"""Test script to verify replay.py works with interactive sessions."""

import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from persistence import SessionStore, list_sessions

def test_replay_compatibility():
    """Test that sessions generated by interactive.py are replayable."""
    
    sessions = list_sessions()
    print(f"Found {len(sessions)} session(s)")
    
    if not sessions:
        print("No sessions to test. Run interactive.py first.")
        return
    
    # Find interactive sessions
    interactive_sessions = [s for s in sessions if s.startswith("s9-interactive-")]
    
    if not interactive_sessions:
        print("No interactive sessions found.")
        print(f"Available sessions: {sessions}")
        return
    
    print(f"\nFound {len(interactive_sessions)} interactive session(s):")
    for sid in interactive_sessions:
        print(f"  {sid}")
    
    # Test the first interactive session
    sid = interactive_sessions[0]
    print(f"\nTesting session: {sid}")
    print("=" * 80)
    
    store = SessionStore(sid)
    
    # Check query
    query = store.read_query()
    print(f"Query: {query[:100] if query else '(none)'}...")
    
    # Check nodes
    nodes = store.read_all_nodes()
    print(f"Nodes: {len(nodes)}")
    
    # Check session directory
    session_dir = Path(f"state/sessions/{sid}")
    print(f"Session dir exists: {session_dir.exists()}")
    
    if session_dir.exists():
        files = list(session_dir.glob("*"))
        print(f"Files in session dir: {len(files)}")
        for f in files[:10]:  # Show first 10 files
            size = f.stat().st_size if f.is_file() else 0
            print(f"  {f.name:30s} {size:>10,} bytes")
    
    # Verify each node can be loaded
    print(f"\nVerifying {len(nodes)} nodes:")
    for i, node in enumerate(nodes[:5], 1):  # Check first 5
        status_icon = "OK" if node.result and node.result.success else "FAIL"
        elapsed = f"{node.result.elapsed_s:.1f}s" if node.result and node.result.elapsed_s else "—"
        print(f"  [{status_icon:4s}] Node {i}: {node.skill:15s} {node.status:10s} {elapsed:>6s}")
    
    if len(nodes) > 5:
        print(f"  ... and {len(nodes) - 5} more nodes")
    
    print("\n" + "=" * 80)
    print("[SUCCESS] Session is valid and replayable!")
    print(f"\nTo replay this session, run:")
    print(f"  python replay.py {sid}")

if __name__ == "__main__":
    test_replay_compatibility()
